# Generated by Django 4.1.7 on 2023-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_books',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество книг в библиотеке'),
        ),
    ]
